package com.qa.tests.ui;

import com.qa.base.BaseTest;
import com.qa.constants.AppConstants;
import com.qa.dataproviders.TestDataProviders;
import com.qa.pages.CartPage;
import com.qa.pages.ContactUsPage;
import com.qa.pages.HomePage;
import com.qa.utils.ExtentManager;
import com.qa.utils.TestDataFactory;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Map;

/**
 * Contact Us form and newsletter subscription.
 *
 * These two features are tested together because they are the site's only two
 * "leave us your details" flows, and both prove their outcome the same way: with a
 * green banner that appears only after the browser has actually posted something.
 *
 * TWO THINGS IN HERE ARE WORTH EXPLAINING IN AN INTERVIEW.
 *
 * 1. The contact form fires a native confirm("Press OK to proceed!"). A native
 *    dialog is not part of the DOM, so until it is answered every Selenium call
 *    against the page throws UnhandledAlertException. The page object therefore
 *    submits and answers the dialog in one method, and hands back the dialog text so
 *    a test can still assert on it. Answering it with "Cancel" instead of "OK" is a
 *    genuine negative case: the form must NOT submit, and that is asserted below.
 *
 * 2. The file upload uses a real temporary file that this class creates at runtime
 *    rather than a fixture committed to the repository. A committed fixture is one
 *    more thing that can go missing on a fresh clone or a CI agent; a file created
 *    in the system temp directory always exists, on every machine, and is deleted
 *    again in teardown.
 *
 * BaseTest gives every method its own browser, so nothing here has to undo a
 * half-filled form left behind by the test before it.
 */
public class ContactSubscriptionTest extends BaseTest {

    /**
     * Expected headings. They are not in AppConstants because nothing outside this
     * class asserts on them, and src/main is frozen. Compared case-insensitively:
     * the site renders both through CSS that upper-cases them, so the rendered text
     * Selenium returns is not necessarily the text in the HTML source.
     */
    private static final String GET_IN_TOUCH_HEADING = "GET IN TOUCH";
    private static final String SUBSCRIPTION_HEADING = "SUBSCRIPTION";

    /** Created once for the whole class; the upload test needs a file that really exists on disk. */
    private Path attachment;

    @BeforeClass(alwaysRun = true)
    public void createTemporaryAttachment() throws IOException {
        attachment = Files.createTempFile("contact-us-attachment-", ".txt");
        Files.writeString(attachment,
                "Attachment generated by ContactSubscriptionTest. Safe to delete.",
                StandardCharsets.UTF_8);
        // Belt and braces: if the JVM is killed before @AfterClass runs, the file
        // still goes away rather than accumulating in the temp directory.
        attachment.toFile().deleteOnExit();
        log.info("Temporary upload fixture created at {}", attachment.toAbsolutePath());
    }

    @AfterClass(alwaysRun = true)
    public void deleteTemporaryAttachment() throws IOException {
        if (attachment != null) {
            Files.deleteIfExists(attachment);
        }
    }

    // ------------------------------------------------------------- Contact Us

    @Test(groups = {"ui", "regression", "contact"},
          dataProvider = "contactUsData",
          dataProviderClass = TestDataProviders.class,
          description = "Filling in the Contact Us form and pressing OK on the confirmation dialog "
                        + "submits the enquiry and shows the success message")
    public void contactFormIsSubmittedForEveryDataRow(Map<String, String> row) {

        ExtentManager.logStep("Data row " + row.get("testCaseId") + " - " + row.get("description"));

        ContactUsPage contactUs = openContactUsPage();

        ExtentManager.logStep("Filling in the enquiry for " + row.get("name"));
        contactUs.fillForm(row.get("name"), row.get("email"), row.get("subject"), row.get("message"));

        ExtentManager.logStep("Submitting the form and accepting the confirmation dialog");
        String alertText = contactUs.submitAndAcceptAlert();

        // Assert on the dialog itself, not only on what happens afterwards: if the
        // site ever changes that wording, the test should say so explicitly rather
        // than fail later with a confusing "success banner not found".
        Assert.assertEquals(alertText, AppConstants.CONTACT_US_ALERT_TEXT,
                "The confirmation dialog for row " + row.get("testCaseId")
                + " did not show the expected text");

        Assert.assertTrue(contactUs.isSuccessMessageVisible(),
                "The success banner did not appear after submitting row " + row.get("testCaseId"));

        Assert.assertEquals(contactUs.getSuccessMessage(), AppConstants.CONTACT_US_SUCCESS_MESSAGE,
                "The success banner text was wrong for row " + row.get("testCaseId"));
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "Pressing Cancel on the Contact Us confirmation dialog abandons the enquiry "
                        + "and no success message is shown")
    public void cancellingTheConfirmDialogDoesNotSubmitTheContactForm() {

        ContactUsPage contactUs = openContactUsPage();

        ExtentManager.logStep("Filling in a valid enquiry that we are then going to abandon");
        contactUs.fillForm(TestDataFactory.randomName(),
                           TestDataFactory.uniqueEmail(),
                           "Cancelled enquiry",
                           TestDataFactory.randomSentence());

        ExtentManager.logStep("Submitting the form but pressing Cancel on the dialog");
        String alertText = contactUs.submitAndDismissAlert();

        Assert.assertEquals(alertText, AppConstants.CONTACT_US_ALERT_TEXT,
                "The dialog shown before cancelling was not the expected confirmation dialog");

        // isSuccessMessageVisible() waits only short.wait (5s) before returning false,
        // so this negative assertion costs seconds rather than the full 20s timeout.
        Assert.assertFalse(contactUs.isSuccessMessageVisible(),
                "Cancelling the confirmation dialog must not submit the form, "
                + "but the success banner appeared anyway");

        Assert.assertTrue(contactUs.isLoaded(),
                "After cancelling, the visitor should still be looking at the Contact Us form");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "An enquiry can be sent with a file attached to it")
    public void contactFormAcceptsAFileAttachment() {

        ContactUsPage contactUs = openContactUsPage();

        ExtentManager.logStep("Filling in an enquiry that carries an attachment");
        contactUs.fillForm(TestDataFactory.randomName(),
                           TestDataFactory.uniqueEmail(),
                           "Enquiry with an attachment",
                           TestDataFactory.randomSentence());

        // A file input is driven with sendKeys on the input itself. Never click it:
        // that opens the operating system's file chooser, which Selenium cannot see.
        ExtentManager.logStep("Attaching " + attachment.getFileName());
        contactUs.attachFile(attachment.toAbsolutePath().toString());

        ExtentManager.logStep("Submitting the form and accepting the confirmation dialog");
        String alertText = contactUs.submitAndAcceptAlert();

        Assert.assertEquals(alertText, AppConstants.CONTACT_US_ALERT_TEXT,
                "The confirmation dialog did not show the expected text on the upload submission");

        Assert.assertTrue(contactUs.isSuccessMessageVisible(),
                "Attaching a file must not stop the enquiry being submitted, "
                + "but no success banner appeared");

        Assert.assertEquals(contactUs.getSuccessMessage(), AppConstants.CONTACT_US_SUCCESS_MESSAGE,
                "The success banner text was wrong after submitting with an attachment");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "The Contact Us page reached from the header shows the 'Get In Touch' heading")
    public void contactPageShowsTheGetInTouchHeading() {

        // Reached by clicking the header link rather than by typing the URL, so this
        // test also covers the navigation a real visitor would use.
        ExtentManager.logStep("Opening Contact Us from the header navigation");
        homePage.header().goToContactUs();
        ContactUsPage contactUs = new ContactUsPage(driver);

        Assert.assertTrue(contactUs.isLoaded(),
                "The Contact Us form was not displayed after clicking the header link");

        Assert.assertEquals(contactUs.getPageTitle(), AppConstants.CONTACT_US_PAGE_TITLE,
                "The browser title of the Contact Us page was wrong");

        Assert.assertEquals(contactUs.getHeading().toUpperCase(Locale.ROOT), GET_IN_TOUCH_HEADING,
                "The Contact Us form heading was not 'Get In Touch'");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "After a successful enquiry the Home button takes the visitor back to the home page")
    public void homeButtonReturnsToTheHomePageAfterASuccessfulEnquiry() {

        ContactUsPage contactUs = openContactUsPage();

        ExtentManager.logStep("Submitting a valid enquiry");
        contactUs.fillForm(TestDataFactory.randomName(),
                           TestDataFactory.uniqueEmail(),
                           "Enquiry before returning home",
                           TestDataFactory.randomSentence());
        contactUs.submitAndAcceptAlert();

        Assert.assertTrue(contactUs.isSuccessMessageVisible(),
                "The success banner is the precondition for this test and it did not appear");

        ExtentManager.logStep("Clicking the Home button offered next to the success message");
        HomePage backHome = contactUs.clickHome();

        Assert.assertTrue(backHome.isLoaded(),
                "The Home button next to the success message did not lead back to the home page");

        Assert.assertEquals(backHome.getPageTitle(), AppConstants.HOME_PAGE_TITLE,
                "The browser title after clicking Home was not the home page title");
    }

    // ---------------------------------------------------------- Subscription

    @Test(groups = {"ui", "regression", "contact"},
          description = "Subscribing to the newsletter from the home page footer confirms the subscription")
    public void subscribingFromTheHomePageFooterShowsTheSuccessMessage() {

        String email = TestDataFactory.uniqueEmail();

        ExtentManager.logStep("Subscribing from the home page footer as " + email);
        homePage.footer().subscribeWith(email);

        Assert.assertTrue(homePage.footer().isSubscriptionSuccessVisible(),
                "No subscription confirmation appeared in the home page footer");

        Assert.assertEquals(homePage.footer().getSubscriptionSuccessMessage(),
                AppConstants.SUBSCRIPTION_SUCCESS_MESSAGE,
                "The home page subscription confirmation text was wrong");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "Subscribing to the newsletter from the cart page footer confirms the subscription")
    public void subscribingFromTheCartPageFooterShowsTheSuccessMessage() {

        // The footer is one shared component, but it is worth proving it works on a
        // second page: the cart renders through a different template, and a broken
        // include there would otherwise go unnoticed.
        ExtentManager.logStep("Opening the cart page");
        CartPage cart = new CartPage(driver).open();
        Assert.assertTrue(cart.isLoaded(), "The cart page did not load, so its footer cannot be tested");

        String email = TestDataFactory.uniqueEmail();
        ExtentManager.logStep("Subscribing from the cart page footer as " + email);
        cart.footer().subscribeWith(email);

        Assert.assertTrue(cart.footer().isSubscriptionSuccessVisible(),
                "No subscription confirmation appeared in the cart page footer");

        Assert.assertEquals(cart.footer().getSubscriptionSuccessMessage(),
                AppConstants.SUBSCRIPTION_SUCCESS_MESSAGE,
                "The cart page subscription confirmation text was wrong");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "The footer of the home page shows the 'Subscription' heading above the e-mail box")
    public void subscriptionHeadingIsVisibleInTheFooter() {

        ExtentManager.logStep("Scrolling to the footer and checking the subscription block");

        Assert.assertTrue(homePage.footer().isSubscriptionHeadingVisible(),
                "The subscription heading was not visible in the footer");

        Assert.assertEquals(homePage.footer().getSubscriptionHeading().toUpperCase(Locale.ROOT),
                SUBSCRIPTION_HEADING,
                "The footer heading above the e-mail box was not 'Subscription'");

        // The box must be a type="email" input; that is what makes the browser reject
        // the malformed address used by the negative test below.
        Assert.assertTrue(homePage.footer().isEmailFieldRequired(),
                "The subscription box should be an HTML5 e-mail input so the browser validates it");
    }

    @Test(groups = {"ui", "regression", "contact"},
          description = "A badly formed e-mail address is rejected by the subscription box and no "
                        + "confirmation is shown")
    public void malformedEmailIsNotAcceptedBySubscriptionBox() {

        // Derived from a generated address with its "@" removed, so the value is still
        // unique per run but can never satisfy the input's type="email" validation.
        // Generating it beats a hardcoded literal: nothing in this class has to be
        // edited when the address format changes.
        String malformedEmail = TestDataFactory.uniqueEmail().replace("@", "-at-");

        ExtentManager.logStep("Trying to subscribe with the malformed address " + malformedEmail);
        homePage.footer().subscribeWith(malformedEmail);

        Assert.assertFalse(homePage.footer().isSubscriptionSuccessVisible(),
                "A malformed e-mail address must not be accepted, but the subscription "
                + "confirmation appeared for '" + malformedEmail + "'");
    }

    // -------------------------------------------------------------- helpers

    /**
     * Every contact test starts from a freshly loaded form. Navigating straight to
     * the URL keeps the tests focused on the form itself - the header link is
     * exercised deliberately by one test above instead of incidentally by all of them.
     */
    private ContactUsPage openContactUsPage() {
        ContactUsPage contactUs = new ContactUsPage(driver).open();
        Assert.assertTrue(contactUs.isLoaded(), "The Contact Us form did not load");
        return contactUs;
    }
}
